services:
  postgres:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate:v4.13.0
    env_file: .env
    entrypoint: []
    depends_on:
      - postgres
    command: migrate -help
  api-server:
    build:
      context: .
      dockerfile: ./docker/api-server/Dockerfile
    ports:
      - 80:4000
    env_file: .env
    depends_on:
      - postgres

volumes:
  postgres_data:
