/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: string;
        };
      };
    };
  };
  "/items": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["service.ItemsListResponse"];
        };
      };
    };
  };
  "/items/{id}": {
    get: {
      parameters: {
        path: {
          /** ID */
          id: unknown;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["service.ItemModel"];
        };
        /** Not Found */
        404: {
          schema: definitions["service.ErrorResponse"];
        };
      };
    };
  };
}

export interface definitions {
  "service.ErrorResponse": {
    message: string;
  };
  "service.ItemModel": {
    id: number;
    name: string;
  };
  "service.ItemsListResponse": {
    count: number;
    items: definitions["service.ItemModel"][];
  };
}

export interface operations {}
