definitions:
  app.ItemModel:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  app.ItemsListResponse:
    properties:
      count:
        type: integer
      items:
        items:
          $ref: '#/definitions/app.ItemModel'
        type: array
    type: object
  httphandler.ErrorResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  title: App API
  version: "1.0"
paths:
  /:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Hello world.
      tags:
      - common
  /items:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/app.ItemsListResponse'
            type: array
      summary: Get items.
      tags:
      - items
  /items/{id}:
    get:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ItemModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httphandler.ErrorResponse'
      summary: Get item by id.
      tags:
      - items
swagger: "2.0"
